### PR TITLE
Update wakeup.py

### PR DESCRIPTION
**Pull request by tmpt1**
for this excellent script to work with fritzos 7.25 this change seems necassary

### CODE REVIEW

**Comment by n0rc** [comment]
Thanks! However, this seems to break compatibility with all versions <7.25. I guess we need to reintroduce version checks then...

**Comment by tmpt1** [comment]
> 
> 
> Thanks! However, this seems to break compatibility with all versions <7.25. I guess we need to reintroduce version checks then...

Sure, I agree to that.

**Comment by tmpt1** [comment]
I added a version check. 
Tested on fritzos 7.25, but I have no fritbox with lower version anymore, so couldn't test it on an older version

**Comment by n0rc** [comment]
The version check should work on <7.25, too. I'll merge your PR and clean up some of the code. Thanks!

**Pull request merged**
